services:
  - type: web
    name: my-simple-chatbot
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
